---
deployment:
  tasks:
    - cd /home/branemlz/repositories/tasksportal
    - npm ci
    - npm run build
    - mkdir -p /home/branemlz/tasksportal.online
    - rm -rf /home/branemlz/tasksportal.online/*
    - cp -a /home/branemlz/repositories/tasksportal/dist/. /home/branemlz/tasksportal.online/
