deployment:
  tasks:
    - export REPOPATH=/home/branemlz/repositories/tasksportal
    - export DEPLOYPATH=/home/branemlz/tasksportal.online
    - /bin/mkdir -p $DEPLOYPATH
    - /usr/bin/npm --prefix $REPOPATH ci
    - /usr/bin/npm --prefix $REPOPATH run build
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R $REPOPATH/dist/. $DEPLOYPATH/
